server:
  port: 8080
spring:
  application:
    name: codecash
  graphql:
    graphiql:
      enabled: true
  datasource:
    url: "jdbc:postgresql://localhost:5432/codecash"
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  cache:
    type: redis
    redis:
      time-to-live: 10m
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false